spring.application.name=apcms_a
spring.main.web-application-type=servlet
server.port=81
server.servlet.context-path=/alpharking/admin

spring.datasource.url=${DB_URL:jdbc:oracle:thin:@192.168.0.39:1521:xe}
# apply when finally deploying
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
# delete when finally deploying
spring.datasource.username=${DB_USERNAME:alpharking}
spring.datasource.password=${DB_PASSWORD:alpharking}

#myBatis mapping
#typeAlias => @Alias("AliasName")
mybatis.type-aliases-package=kr.co.alpharking.dto

#mapper => src/main/resources : classpath
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.jdbc-type-for-null=null
mybatis.configuration.map-underscore-to-camel-case=true

#fileupload Configure
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=215MB
spring.servlet.multipart.file-size-threshold=2KB
#spring.servlet.multipart.location=D:\\ictstudy\\springboot\\workspace\\myictstudy0629\\src\\main\\resources\\static\\imgfile
# -v ~/upload:/app/upload  => docker volumn
spring.servlet.multipart.location=${UPLOAD_PATH:./upload}
#spring.servlet.multipart.location=/app/upload

#SMTP Mail Setting
spring.mail.host=smtp.naver.com
spring.mail.port=465
# spring.mail.username=YouEmail@naver.com
# spring.mail.password=YouEmailPWD
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.default-encoding=utf-8
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=true

#spring.data.redis.host=localhost
#spring.data.redis.port=6379

spring.output.ansi.enabled=always